ignore-paths:
  - docs
  - data
  - static

pep8:
  options:
    max-line-length: 200

pylint:
  options:
    max-line-length: 200

  disable:
    - R0901 # Too many ancestors - because of django libraries inheritance
    - R1705 # allow no-else-return

pyflakes:
  disable:
    - F999 # allow .* imports because of settings

uses:
    - django
    - celery
