# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('core', '0002_auto_20170513_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='rating_facilities', to='utils.Tag'),
        ),
        migrations.AddField(
            model_name='spot',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='spot_facilities', to='utils.Tag'),
        ),
    ]
