# Generated by Django 2.0.2 on 2018-04-03 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170703_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rating_facilities', to='utils.Tag'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spot',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='spot_facilities', to='utils.Tag'),
        ),
    ]
