// Generated by CoffeeScript 1.9.0
(function() {
  $(function() {
    if (window.chrome) {
      $('.banner li').css('background-size', '100% 100%');
    }
    return $('.banner').unslider({
      speed: 1500,
      arrows: false,
      fluid: true,
      dots: true
    });
  });

}).call(this);
