// Generated by CoffeeScript 1.9.0
(function() {
  $(function() {
    if (window.chrome) {
      $('.banner li').css('background-size', '100% 100%');
    }
    $('.banner').unslider({
      speed: 1500,
      arrows: false,
      fluid: true,
      dots: true
    });
    return $('a[href^="#"]').click(function() {
      var pos, target;
      target = $($(this).attr('href'));
      pos = target.offset();
      if (pos) {
        $('html, body').animate({
          scrollTop: pos.top,
          scrollLeft: pos.left
        }, 1500);
      }
      return false;
    });
  });

}).call(this);
