// Generated by CoffeeScript 1.9.0
(function() {
  $(function() {
    if (window.chrome) {
      $('.banner li').css('background-size', '100% 100%');
    }
    $('.banner').unslider({
      speed: 1500,
      arrows: false,
      fluid: true,
      dots: true
    });
    return $('a.show-menu').on('click', function(e) {
      e.preventDefault();
      return $('.initialy-invisible').show(900);
    });
  });

}).call(this);
