// Generated by CoffeeScript 1.9.0
(function() {
  $(function() {
    $('span.rating').raty({
      size: 24,
      scoreName: 'friendly_rate',
      starOff: STATIC_URL + 'star-off-big.png',
      starHalf: STATIC_URL + 'star-half-big.png',
      starOn: STATIC_URL + 'star-on-big.png',
      score: function() {
        return $(this).attr('data-score');
      },
      readOnly: function() {
        return !window.isAuthenticated;
      }
    });
    return $("#map_canvas_spot_detail").gmap({
      'scrollwheel': false
    }).bind("init", function(evt, map) {
      $("#map_canvas_spot_detail").gmap("addMarker", {
        position: new google.maps.LatLng(LAT, LON),
        bounds: true
      });
      return $("#map_canvas_spot_detail").gmap("option", "zoom", 17);
    });
  });

}).call(this);
