// Generated by CoffeeScript 1.9.0
(function() {
  $(function() {
    return $("#map_canvas_spot_detail").gmap({
      'scrollwheel': false
    }).bind("init", function(evt, map) {
      $("#map_canvas_spot_detail").gmap("addMarker", {
        position: new google.maps.LatLng(LAT, LON),
        bounds: true
      });
      return $("#map_canvas_spot_detail").gmap("option", "zoom", 17);
    });
  });

}).call(this);
